#!/bin/bash
# EOS Platform Quick Reference
# Location: /home/ubuntu/eosplatform/

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║        STEENSMA EOS PLATFORM - QUICK REFERENCE            ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "🌐 URL: https://eos.coresteensma.com"
echo "🔐 Auth: Same as shop.coresteensma.com"
echo "📂 Location: /home/ubuntu/eosplatform/"
echo "🔌 Port: 5002"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "SERVICE STATUS"
echo "═══════════════════════════════════════════════════════════"
echo ""
systemctl is-active --quiet eosplatform && echo "✓ App Service:  RUNNING" || echo "✗ App Service:  STOPPED"
systemctl is-active --quiet eosplatform-gdrive-sync && echo "✓ Sync Service: RUNNING" || echo "✗ Sync Service: STOPPED"
systemctl is-active --quiet nginx && echo "✓ Nginx:        RUNNING" || echo "✗ Nginx:        STOPPED"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "DATA FILES"
echo "═══════════════════════════════════════════════════════════"
echo ""
ls -lh /home/ubuntu/eosplatform/datasheets/*.csv 2>/dev/null | awk '{print $9, "(" $5 ")", $6, $7, $8}'
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "COMMON COMMANDS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Restart app:          sudo systemctl restart eosplatform"
echo "View logs:            journalctl -u eosplatform -f"
echo "Upload data:          scp file.csv ubuntu@server:~/eosplatform/datasheets/"
echo "Test API:             curl http://localhost:5002/api/summary"
echo "Check health:         curl http://localhost:5002/health"
echo "Start sync:           sudo systemctl start eosplatform-gdrive-sync"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "DOCUMENTATION"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📘 Full Guide:        /home/ubuntu/eosplatform/README.md"
echo "📗 Success Doc:       /home/ubuntu/eosplatform/DEPLOYMENT_SUCCESS.md"
echo "📙 This Script:       /home/ubuntu/eosplatform/status.sh"
echo ""
